### PR TITLE
Tidied up Sch by using labels

### PR DESCRIPTION
**Pull request by ryanm101**
Clean up in the Schematic to make it more readable.

### CODE REVIEW

**Comment by paulocode** [comment]
Hi! I'm a beginner KiCad user here. Can you please point out the specifically change you made? I might be missing them.

**Comment by ryanm101** [comment]
You'll need to open in Kicad to see but instead of having the wires drawn in the Schematic I've change it to use labels. This makes it much easier to see where wires are going. It should make no change to the PCB just the Schematatic.

Before 
Screenshot 2023-02-20 at 14 01 14

After:

Screenshot 2023-02-20 at 14 00 40


If you click a label / wire you can use \` to highlight everywhere it connects. 
I've also marked unconnected points with `x` so they are properly terminated.

**Comment by ryanm101** [comment]
I've used labels named per destination better would likely be to use the names of the actual connections on the PCB but as a first pass this is fine.

**Comment by paulocode** [comment]
Turns out I was on the wrong branch. Thanks for this, nice work!

**Pull request merged**
